# Generated by Django 5.2 on 2025-04-26 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='type',
            new_name='entry_type',
        ),
    ]
