# Generated by Django 5.2 on 2025-05-02 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_category_category_type_category_is_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('bills', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grocery', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('food', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('health', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('eatingout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transportation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gifts', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
