# Generated by Django 5.2 on 2025-05-03 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_budget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
